import { build, type Plugin } from 'esbuild'
import { existsSync } from 'node:fs'
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const MARKER = 'generated by `nimbus vendor`'

interface VendorOpts {
  root: string
  entry: string
}

export async function vendor({ root, entry }: VendorOpts) {
  const entryFile = path.join(root, entry)
  if (!existsSync(entryFile)) {
    throw new Error(`${entry} not found in ${root} (pass --entry if your bot lives elsewhere)`)
  }

  // 1. drop the prebuilt runtime into lib/_vendor. dist/index.js is already a
  // self-contained ESM bundle whose only imports are 'sdk' / 'sdk/db'.
  const runtime = fileURLToPath(new URL('./index.js', import.meta.url))
  const vendorDir = path.join(root, 'lib', '_vendor')
  await mkdir(vendorDir, { recursive: true })
  await copyFile(runtime, path.join(vendorDir, 'nimbus.js'))

  // 2. load the user's bot to see which update types it subscribes to
  const bot = await loadBot(root, entryFile)
  const types: string[] = bot.updateTypes()
  if (types.length === 0) {
    console.warn('bot has no handlers registered, no shims to generate')
    return
  }

  // 3. shims. platform imports are bare names, so 'lib/bot' not './lib/bot.js'
  // TODO-VERIFY: bare imports of nested paths like lib/_vendor/nimbus
  const botModule = entry.replace(/\.js$/, '')
  const handlersDir = path.join(root, 'handlers')
  await mkdir(handlersDir, { recursive: true })

  for (const type of types) {
    const file = path.join(handlersDir, `${type}.js`)
    if (existsSync(file) && !(await readFile(file, 'utf8')).includes(MARKER)) {
      console.warn(`handlers/${type}.js exists and is not ours, skipping`)
      continue
    }
    const src = `// ${MARKER} -- do not edit\nimport bot from '${botModule}'\n\nexport default (payload, ctx) => bot.handle('${type}', payload, ctx)\n`
    await writeFile(file, src)
  }

  console.log(`vendored runtime -> lib/_vendor/nimbus.js`)
  console.log(`handlers: ${types.join(', ')}`)
}

// the bot module uses platform-style bare imports, so it can't be import()ed
// directly under node. bundle it to a temp file with sdk stubbed out first.
async function loadBot(root: string, entryFile: string) {
  const outfile = path.join(root, '.nimbus', 'bot.analysis.mjs')
  await build({
    entryPoints: [entryFile],
    bundle: true,
    format: 'esm',
    outfile,
    logLevel: 'silent',
    plugins: [projectResolver(root)],
  })

  try {
    const mod = await import(pathToFileURL(outfile).href + `?t=${Date.now()}`)
    const bot = mod.default
    if (typeof bot?.updateTypes !== 'function') {
      throw new Error(`${path.basename(entryFile)} must default-export a Bot instance`)
    }
    return bot
  } finally {
    await rm(path.dirname(outfile), { recursive: true, force: true })
  }
}

function projectResolver(root: string): Plugin {
  return {
    name: 'nimbus-project',
    setup(b) {
      b.onResolve({ filter: /^sdk(\/db)?$/ }, (args) => ({ path: args.path, namespace: 'sdk-stub' }))
      b.onLoad({ filter: /.*/, namespace: 'sdk-stub' }, () => ({ contents: SDK_STUB, loader: 'js' }))
      b.onResolve({ filter: /^(lib|handlers)\/|^schema$/ }, (args) => {
        let p = path.join(root, args.path)
        if (!path.extname(p)) p += '.js'
        return { path: p }
      })
    },
  }
}

// inert stand-ins: importing is fine, touching them at module top level is not
const SDK_STUB = `
const dead = new Proxy(function () {}, {
  get: (_, prop) => (prop === Symbol.toPrimitive ? () => '[sdk stub]' : dead),
  apply: () => dead,
})
export const api = dead
export const db = dead
export const fetch = dead
export class BotApiError extends Error {}
export const table = dead, text = dead, integer = dead, real = dead, numeric = dead, blob = dead
export const boolean = dead, json = dead
export const eq = dead, ne = dead, gt = dead, gte = dead, lt = dead, lte = dead
export const like = dead, isNull = dead, inArray = dead, and = dead, or = dead, sql = dead
`
